
login:
	terraform login
	
init:
	terraform init

plan:
	terraform plan

apply:
	terraform apply -auto-approve

destroy:
	terraform destroy -auto-approve

clean:
	@echo "rm .terraform"
	@rm -f .terraform.lock.hcl
	@rm -rf .terraform
